In [19]:
import numpy as np

np.version.full_version



'1.9.2'

In [20]:
a = np.arange(20)
a
a.reshape(4, 5)
# reshape 参数, 先分行, 再分列, 由大到小
a = a.reshape(2, 2, 5)
# a.reshape(2, 3, 5) 
# => ValueError: total size of new array must be unchanged

In [23]:
a.dtype

dtype('int32')

In [26]:
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [29]:
np.zeros((4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [36]:
b = np.random.rand(5)
print(b)
b+3

[ 0.08574088  0.54079727  0.72982245  0.54845066  0.86058918]


array([ 3.08574088,  3.54079727,  3.72982245,  3.54845066,  3.86058918])

In [43]:
b
b.sum()
b.max()
b.min()



0.085740880711172807

In [49]:
a = np.arange(20)
a = a.reshape(2, 2, 5)
print(a)
a.max(axis=2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


array([[ 4,  9],
       [14, 19]])

NumPy同时提供了矩阵对象（matrix）。
矩阵对象和数组的主要有两点差别：一是矩阵是二维的，而数组的可以是任意正整数维；二是矩阵的'*'操作符进行的是矩阵乘法，乘号左侧的矩阵列和乘号右侧的矩阵行要相等，而在数组中'*'操作符进行的是每一元素的对应相乘，乘号两侧的数组每一维大小需要一致。数组可以通过asmatrix或者mat转换为矩阵，或者直接生成也可以


In [53]:
a = np.arange(20).reshape(4, 5)
a = np.asmatrix(a)
type(a)
a
b = np.matrix('1.0 2.0; 3.0 4.0')
b

matrix([[ 1.,  2.],
        [ 3.,  4.]])

In [57]:
b = np.arange(2, 45, 3).reshape(5, 3)
b = np.mat(b)
b

matrix([[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26],
        [29, 32, 35],
        [38, 41, 44]])

In [59]:
np.arange(2, 45, 3)  # arange 指定步长
np.linspace(0, 2, 9) # linspace 指定一维数组的长度

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

### 数组元素访问

In [61]:
a = np.array([[3.2, 1.5], [2.5, 4]])
a[0][1]
a[0, 1]

1.5

In [67]:
a = np.array([[3.2, 1.5], [2.5, 4]])
b = a.copy() # 深拷贝??
a[0][1] = 2.0

print(a, b, sep='\n\n')

[[ 3.2  2. ]
 [ 2.5  4. ]]

[[ 3.2  1.5]
 [ 2.5  4. ]]


In [69]:
a = np.arange(20).reshape(4, 5)

print(a)

print("the 2nd and 4th column of a:")
a[:,[1,3]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
the 2nd and 4th column of a:


array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [71]:
a[:, 2][a[:, 0] > 5]
# 取出第一列大于5的元素（10和15）对应的第三列元素（12和17）

array([12, 17])

In [73]:
loc = np.where(a==11)
loc
# print a[loc[0][0], loc[1][0]]

(array([2], dtype=int32), array([1], dtype=int32))