In [8]:
import numpy as np
from numpy import linalg as LA



self_X_train = np.random.random([5, 17])
X = np.random.random([3, 17])
print(self_X_train)
print(X)


[[ 0.24849118  0.32384153  0.82245058  0.07189131  0.93022709  0.69114224
   0.66224996  0.63363745  0.12974682  0.22073688  0.96135745  0.02788211
   0.18580796  0.1752547   0.85068773  0.5248464   0.08725723]
 [ 0.51379339  0.6593143   0.71306982  0.66471537  0.23687258  0.77917201
   0.35806579  0.78125582  0.55680238  0.51567913  0.50288548  0.15114914
   0.11786493  0.14777612  0.89942014  0.45748436  0.95872739]
 [ 0.66187208  0.64287388  0.69318935  0.96526352  0.6370837   0.46799625
   0.26158846  0.66111944  0.89982464  0.92060649  0.22163271  0.63225726
   0.27982596  0.73397619  0.48182034  0.27075111  0.7971586 ]
 [ 0.81289191  0.78093928  0.11644754  0.19502362  0.35694832  0.68234742
   0.21764489  0.80781605  0.72211718  0.92188813  0.47291779  0.91890456
   0.52971298  0.94236447  0.7072343   0.25328047  0.06004317]
 [ 0.73545473  0.59898369  0.5242941   0.19584563  0.46430714  0.40598322
   0.28947179  0.44068219  0.30391773  0.3397772   0.2010296   0.65627605
   0.927

In [7]:
def compute_distances_one_loop(X):
    
    num_test = X.shape[0]
    num_train = self_X_train.shape[0]
    dists = np.zeros((num_test, num_train))
    for i in range(num_test):

        
        x = X[i]
        line = self_X_train
        dists[i, :] = line

    return dists

self_X_train

array([[ 0.20101922,  0.01121911,  0.59107871,  0.99513641,  0.197388  ,
         0.7835227 ,  0.92231173,  0.83576214,  0.03491435,  0.94463707,
         0.8121295 ,  0.85909111,  0.67530497,  0.07212098,  0.2771095 ,
         0.37379527,  0.50944329],
       [ 0.24630844,  0.37793335,  0.80689706,  0.29904074,  0.87034125,
         0.8475428 ,  0.42542375,  0.03932686,  0.44234333,  0.96018766,
         0.56067945,  0.29766432,  0.94826417,  0.91264168,  0.57602717,
         0.06389145,  0.12203307],
       [ 0.72126938,  0.08486818,  0.79551007,  0.31237405,  0.18839186,
         0.80351407,  0.21771745,  0.29064931,  0.71741333,  0.26820918,
         0.54938391,  0.1650147 ,  0.52119666,  0.06820994,  0.44300712,
         0.15595129,  0.89523762],
       [ 0.71714554,  0.22264972,  0.98667759,  0.86449925,  0.98237525,
         0.8602817 ,  0.15584912,  0.61958722,  0.69150537,  0.02944407,
         0.45282972,  0.56857547,  0.22268614,  0.82171918,  0.53881507,
         0.91037054

In [11]:
m = np.arange(8).reshape(2,2,2)
print(m)
a = LA.norm(m, axis=(1,2))
print(a)


b = LA.norm(m[0, :, :]), LA.norm(m[1, :, :])
print(b)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[  3.74165739  11.22497216]
(3.7416573867739413, 11.224972160321824)


In [12]:
m1 = np.arange(4).reshape(2,2)
print(m)
LA.norm(m)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


11.832159566199232

In [41]:
np.argsort(x, axis=1)

array([[0, 2, 1],
       [2, 1, 0]], dtype=int32)

In [43]:
a = x[0]
a

array([ 0.1 ,  0.16,  0.14])

In [46]:
a
list(np.argsort(a)[:2])

[0, 2]

In [52]:
b = np.array([11,11,22,22,22])

np.bincount(b).argmax()

IndexError: invalid index to scalar variable.