In [39]:
import numpy as np


x = np.array([[0.1, .16, .14], [.22, .12, .11]])
x


array([[ 0.1 ,  0.16,  0.14],
       [ 0.22,  0.12,  0.11]])

In [40]:
np.argsort(x, axis=0)

array([[0, 1, 1],
       [1, 0, 0]], dtype=int32)

In [41]:
np.argsort(x, axis=1)

array([[0, 2, 1],
       [2, 1, 0]], dtype=int32)

In [43]:
a = x[0]
a

array([ 0.1 ,  0.16,  0.14])

In [46]:
a
list(np.argsort(a)[:2])

[0, 2]

In [52]:
b = np.array([11,11,22,22,22])

np.bincount(b).argmax()

IndexError: invalid index to scalar variable.